variables:
  GIT_DEPTH: 1

stages:
  - deploy

deploy_job:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker-compose build
    - echo "----- DOCKER IMAGES BUILT -----"
    - docker-compose up
    - echo "-- DOCKER CONTAINERS STARTED --"
  tags:
    - docker
  timeout: 2h
