name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настройка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Собираем все сервисы
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      # 5. Запускаем контейнеры
      - name: Run Docker containers
        run: docker-compose -f docker-compose.yml up -d

      # 6. Проверяем доступность сервисов (опционально)
      - name: Check services
        run: |
          sleep 10  # Даём время на старт
          curl -f http://localhost:5000/ || exit 1
          curl -f http://localhost:5001/ || exit 1
          curl -f http://localhost:5002/ || exit 1
          curl -f http://localhost:5003/ || exit 1

      # 7. Останавливаем контейнеры
      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down